/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
    const ref = useRef()
  const { nodes, materials } = useGLTF('/suzanne.gltf')

useFrame((state)=> {
    ref.current.position.y = state.pointer.y *4
    ref.current.position.x = state.pointer.x *4
})
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suzanne.geometry}
        material={nodes.Suzanne.material}
        position={[0, 0.189, -0.043]}
      />
    </group>
  )
}

useGLTF.preload('/suzanne.gltf')
